version: '3.4'

services:
  taxadejuros.api:
    image: ${DOCKER_REGISTRY-}taxadejurosapi
    build:
      context: .
      dockerfile: TaxaDeJuros.API\Dockerfile
    ports:
      - "5108:80"

  calculodejuros.api:
    image: ${DOCKER_REGISTRY-}calculodejurosapi
    build:
      context: .
      dockerfile: CalculoDeJuros.API\Dockerfile
    ports:
      - "5104:80"
    depends_on:
      - taxadejuros.api
  calculodejuros.integrationtests:
    image: ${DOCKER_REGISTRY-}calculodejurosintegrationtests
    build:
      context: .
      dockerfile: CalculoDeJuros.IntegrationTests\Dockerfile
    entrypoint: dotnet test
    depends_on:
      - taxadejuros.api
      - calculodejuros.api

